import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { VideoDataPage } from "../../src/renderer/components/VideoDataPage";
import type { VideoDataQuery, VideoDataRow } from "../../src/shared/videoDataTable";
const video = { id: "v1", filename: "one.mp4", path: "F:\\one.mp4", directory: "F:\\", sizeBytes: 100, durationMs: null, importedAt: "2026-09-08T00:00:00.000Z", sourceType: "local", sourcePath: "F:\\", metadataStatus: "ready" } as VideoDataRow;
beforeEach(() => localStorage.clear());
it("selects all filtered results without loading all rows and exports exclusions", async () => {
  const load = vi.fn(async (query: VideoDataQuery) => ({ items: [{ ...video, id: `v${query.page}`, filename: `${query.page}.mp4` }], totalCount: 320000, totalBytes: 32000000, totalPages: 3200, page: query.page, pageSize: query.pageSize }));
  const exportCsv = vi.fn(async () => ({ cancelled: false, count: 319999, path: "test.csv" }));
  render(<VideoDataPage load={load} exportCsv={exportCsv} folders={[]} onDetails={vi.fn()} onDiagnostic={vi.fn()} />);
  await screen.findByText("1.mp4");
  fireEvent.click(screen.getByRole("button", { name: "选择全部筛选结果" }));
  expect(load).toHaveBeenCalledTimes(1);
  fireEvent.click(screen.getByRole("checkbox", { name: "选择 1.mp4" }));
  fireEvent.click(screen.getByRole("button", { name: "下一页" }));
  await screen.findByText("2.mp4");
  expect(screen.getByRole("checkbox", { name: "选择 2.mp4" })).toBeChecked();
  fireEvent.click(screen.getByRole("button", { name: "导出选中 CSV" }));
  await waitFor(() => expect(exportCsv).toHaveBeenCalledWith(expect.objectContaining({ page: 2 }), { all: true, ids: [], excludedIds: ["v1"] }));
  expect(document.querySelector("img")).toBeNull();
});
it("clears selection when filters change and opens details", async () => {
  const load = vi.fn(async (query: VideoDataQuery) => ({ items: [video], totalCount: 1, totalBytes: 100, totalPages: 1, page: query.page, pageSize: query.pageSize }));
  const details = vi.fn();
  render(<VideoDataPage load={load} exportCsv={vi.fn()} folders={[]} onDetails={details} onDiagnostic={vi.fn()} />);
  await screen.findByText("one.mp4");
  fireEvent.click(screen.getByRole("checkbox", { name: "全选本页" }));
  fireEvent.click(screen.getByRole("button", { name: "one.mp4" }));
  expect(details).toHaveBeenCalledWith(video);
  fireEvent.change(screen.getByLabelText("状态"), { target: { value: "missing" } });
  await waitFor(() => expect(load).toHaveBeenLastCalledWith(expect.objectContaining({ status: "missing", page: 1 })));
  expect(screen.getByRole("button", { name: "导出选中 CSV" })).toBeDisabled();
});
